### ISSUE TITLE
In China, Android device  aren't contain Google Play，Running the sample will create bug as below：

### ISSUE THREAD

**Issue by winterbao** [uninstallio/android-sdk#5]
06-26 19:54:22.287: E/AndroidRuntime(31648): Process: com.example.uninstalldemo, PID: 31648
06-26 19:54:22.287: E/AndroidRuntime(31648): java.lang.NoClassDefFoundError: com.google.android.gms.common.GooglePlayServicesUtil
06-26 19:54:22.287: E/AndroidRuntime(31648):    at com.notikum.notifypassive.utils.NotiphiUtility.isGooglePlayServicesAvailable(NotiphiUtility.java:255)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at com.notikum.notifypassive.utils.NotiphiUtility.registerWithGCM(NotiphiUtility.java:75)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at com.notikum.notifypassive.UninstallSession.init(UninstallSession.java:56)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at com.example.uninstalldemo.MainActivity.onCreate(MainActivity.java:28)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.app.Activity.performCreate(Activity.java:5600)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.app.ActivityThread.access$900(ActivityThread.java:174)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.os.Looper.loop(Looper.java:146)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at android.app.ActivityThread.main(ActivityThread.java:5748)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at java.lang.reflect.Method.invokeNative(Native Method)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at java.lang.reflect.Method.invoke(Method.java:515)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
06-26 19:54:22.287: E/AndroidRuntime(31648):    at dalvik.system.NativeStart.main(Native Method)

**Comment by alokmishra** [comment]
This SDK is not meant for China.

**Comment by winterbao** [comment]
Are you not going to support China's Android equipment?
