### ISSUE TITLE
Android 5.0 above system can't work normally.

### ISSUE THREAD

**Issue by winterbao** [uninstallio/android-sdk#6]
Android 5.0 above system can't work normally.

**Comment by alokmishra** [comment]
What is the exact issue ?

**Comment by mepurush** [comment]
Hi Which version of Google Play Services the Library is using.? App is crashing due to this below exception: 
java.lang.IncompatibleClassChangeError: The method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
            at com.notikum.notifypassive.utils.LastKnownLocation.connectToPlayService(LastKnownLocation.java:28)
            at com.notikum.notifypassive.utils.LastKnownLocation.<init>(LastKnownLocation.java:22)
            at com.notikum.notifypassive.UninstallSession.init(UninstallSession.java:63)

I'm using Google Play services 7.8.0.
