### ISSUE TITLE
Which version of Google Play Service we have to use when integrating the Uninstallio. 

### ISSUE THREAD

**Issue by mepurush** [uninstallio/android-sdk#7]
As per the documentation 
Note:: Google Play Services must be compiled against version 6.5 or above.
I'm using version 7.8.0 Still the app crashes
exception: 
java.lang.IncompatibleClassChangeError: The method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
at com.notikum.notifypassive.utils.LastKnownLocation.connectToPlayService(LastKnownLocation.java:28)
at com.notikum.notifypassive.utils.LastKnownLocation.(LastKnownLocation.java:22)
at com.notikum.notifypassive.UninstallSession.init(UninstallSession.java:63)

**Comment by yeswanth** [comment]
I have the same issue with 7.8.0. Updated to 8.3.0 and the issue is no longer there.
