### ISSUE TITLE
UninstallGCMIntentService: IllegalStateException due to null Context

### ISSUE THREAD

**Issue by GReaper** [uninstallio/android-sdk#9]
Today I've received this __crash in my app due to Uninstall.io:__
````
Fatal Exception: java.lang.IllegalArgumentException: Context must not be null.
       at com.songline.uninstall.segmentIO.UninstallAnalytics.with(UninstallAnalytics.java:115)
       at com.songline.uninstall.utils.UninstallGCMResponse.gcmResponse(UninstallGCMResponse.java:42)
       at com.songline.uninstall.services.UninstallGCMIntentService.onHandleIntent(UninstallGCMIntentService.java:24)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
````

__What I've done was:__
- I updated my app version (from Google Play) which contained the Uninstall.io SDK.
- I used my phone along the day.
- I put my phone in airplane mode along the night, from 21:30pm (CET) until 07:45am (CET). 
- When I switched off the airplane mode, I immediately got this crash, even without opening my app. 

__Mi device__ is a BQ M5, which uses Android 6.0.1.

__Update 1:__
- I confirm that we have received more crashes like this with our closed beta. Another one was yesterday at about 23:00pm in a Nexus 5X. It was only having the application in the background but without airplane mode.

**Comment by ashishraval21** [comment]
Hey @GReaper,

Thanks for Reaching us about the crashes you got in your app.

This is happening because of your app is received push notification before initialise the uninstall.io sdk. but we are happy to inform that we were solved this problem and now you can go with new Jar file or Gradle  Build  which is described below.

**Gradle : 'com.songline.uninstall:app:12.3.8'**
Jars : [https://github.com/uninstallio/android-sdk/tree/master/jars](url)

**Comment by GReaper** [comment]
Thank you @ashishraval21 , I'll force that version. What worries me is that we were using `compile  'com.songline.uninstall:app:12.3.+'` in Gradle.
